---
title: "Path analysis"
author: "ZHAO Kai"
header-includes: \usepackage[mono=false]{libertine}
output: html_document 
fontsize: 10pt
mainfont: libertine
sansfont: libertine
---

## Path analysis

Path analysis regarding column_factor

```{r eval=FALSE}
setwd("/Users/zhaokai/data/Results/ageing")

load("ageing_dataset_annotated_with_phenotypes_filtered.RData")
confounders <- dataset[ ,2:4]
dataset <- dataset[, -(1:4)]

cfd1 <- as.integer(confounders[[1]])
cfd2 <- as.integer(confounders[[2]])
cfd3 <- as.integer(confounders[[3]])

# our fitted model 
load("gene_expression_iMF_L1_penalty_25v2.RData")
attach(fitted_obj)

load("ageing_path_analysis_gene.RData")
load("ageing_path_analysis_disease.RData")
load("ageing_path_analysis_tissue.RData")
load("ageing_path_analysis_donor.RData")
```

```{r eval=FALSE}
row_factor <- disease_factor[cfd1, ] + tissue_factor[cfd2, ] + donor_factor[cfd3, ] + disease_factor[cfd1, ] * tissue_factor[cfd2, ]

coeff_matrix <- matrix(0, nrow = nrow(column_factor), ncol = ncol(column_factor))
pval_matrix <- matrix(0, nrow = nrow(column_factor), ncol = ncol(column_factor))

for(i in 1:ncol(dataset)){
    data <- data.frame(response = dataset[[i]], row_factor)
    fit <- glm(response ~., family = "gaussian", data = data)
    coeff_matrix[,i] <- unname(coefficients(fit))[-1]
    pval_matrix[,i] <- coef(summary(fit))[-1,4]
}

save(coeff_matrix, pval_matrix, file = "ageing_path_analysis_gene.RData")
```

Path analysis regarding disease factor

```{r eval=FALSE}
residual <- trainset - (donor_factor[cfd3, ] + tissue_factor[cfd2, ]) %*% column_factor

disease_result <- lapply(1:2, function(i) {
    idx <- which(cfd1 == i)
    cfd2_idx <- cfd2[idx]
    n_element <- sum(indicator[idx, ])

    result <- lapply(1:length(idx), function(k){
        selected <- (indicator[idx[k], ] != 0)
        cbind(residual[idx[k], selected], t(column_factor[, selected] * (1 +  tissue_factor[cfd2_idx[k],])))
    })
    data <- data.frame(do.call(rbind, result)) 
    colnames(data)[1] <- "response"
    fit <- glm(response ~., family = "gaussian", data = data)
    coeff <- unname(coefficients(fit))[-1]
    pvalues <- coef(summary(fit))[-1,4]
    cbind(coeff, pvalues)
})

save(disease_result, file = "ageing_path_analysis_disease.RData")
```

Path analysis regarding tissue factor

```{r eval=FALSE}
residual <- trainset - (donor_factor[cfd3, ] + disease_factor[cfd1, ]) %*% column_factor

tissue_result <- lapply(1:8, function(i) {
    idx <- which(cfd2 == i)
    cfd1_idx <- cfd1[idx]
    n_element <- sum(indicator[idx, ])

    result <- lapply(1:length(idx), function(k){
        selected <- (indicator[idx[k], ] != 0)
        cbind(residual[idx[k], selected], t(column_factor[, selected] * (1 +  disease_factor[cfd1_idx[k],])))
    })
    data <- data.frame(do.call(rbind, result)) 
    colnames(data)[1] <- "response"
    fit <- glm(response ~., family = "gaussian", data = data)
    coeff <- unname(coefficients(fit))[-1]
    pvalues <- coef(summary(fit))[-1,4]
    cbind(coeff, pvalues)
})
save(tissue_result, file = "ageing_path_analysis_tissue.RData")
```

```{r eval=FALSE}
residual <- trainset - (disease_factor[cfd1, ] + tissue_factor[cfd2, ] + disease_factor[cfd1, ] * tissue_factor[cfd2, ]) %*% column_factor

donor_result <- lapply(1:nrow(donor_factor), function(i) {
    idx <- which(cfd3 == i)
    n_element <- sum(indicator[idx, ])

    result <- lapply(1:length(idx), function(k){
        selected <- (indicator[idx[k], ] != 0)
        cbind(residual[idx[k], selected], t(column_factor[, selected]))
    })
    data <- data.frame(do.call(rbind, result)) 
    colnames(data)[1] <- "response"
    fit <- glm(response ~., family = "gaussian", data = data)
    coeff <- unname(coefficients(fit))[-1]
    pvalues <- coef(summary(fit))[-1,4]
    cbind(coeff, pvalues)
})
save(donor_result, file = "ageing_path_analysis_donor.RData")
```

```{r eval=FALSE}
sample_num <- 18
latent_var_num <- 10
gene_num <- 20

sample_idx <- which(cfd3 %in% 1:5)

cfd1_idx <- cfd1[sample_idx]
cfd2_idx <- cfd2[sample_idx]
cfd3_idx <- cfd3[sample_idx]

donor_num <- length(unique(cfd3_idx))
tissue_num <- length(unique(cfd2_idx))
phenotype_num <- length(unique(cfd1_idx))

sample <- create_node_df(n = sample_num,
                         type = "X",
                         label = paste0("X", seq(sample_num)),
                         fillcolor = "green", 
                         shape = "oval")

donor <- create_node_df(n = donor_num,
                        type = "D",
                        label = paste0("D", seq(donor_num)),
                        fillcolor = "pink",
                        shape = "circle")

tissue <- create_node_df(n = tissue_num,
                         type = "T",
                         label = paste0("T", seq(tissue_num)),
                         fillcolor = "PowderBlue",
                         shape = "circle")

phenotype <- create_node_df(n = phenotype_num,
                            type = "P",
                            label = paste0("P", seq(phenotype_num)),
                            fillcolor = "Gold",
                            shape = "circle")

# latent <- create_node_df(n = latent_var_num,
#                          type = "H",
#                          label = paste0("H", seq(latent_var_num)),
#                          fillcolor = "gray", 
#                          shape = "square")

# genes <- create_node_df(n = gene_num,
#                         type = "V",
#                         label = paste0("V", seq(gene_num)),
#                         fillcolor = "Azure",
#                         shape = "circle")

nodes <- combine_ndfs(sample, donor, tissue, phenotype, latent, genes)
```

## data preparations

```{r eval=FALSE}

rownames(nodes) <- nodes$label
rownames(nodes)[1:18] <- paste0("X", sample_idx)
sample_id <- nodes[paste0("X", sample_idx), 1]
donor_id <- nodes[paste0("D", cfd3_idx), 1]
tissue_id <- nodes[paste0("T", cfd2_idx), 1]
phenotype_id <- nodes[paste0("P", cfd1_idx), 1]

# donor_edges <- create_edge_df(sample_id, donor_id, style = "dashed")
# tissue_edges <- create_edge_df(sample_id, tissue_id, style = "dashed")
# phenotype_edges <- create_edge_df(sample_id, phenotype_id, style = "dashed")
# 
# edges <- combine_edfs(donor_edges, tissue_edges, phenotype_edges)
# 
# # Combine edges and nodes
# my_graph <- create_graph(
#   nodes = nodes,
#   edges_df = edges,
#   directed = F)
# 
# # We can plot the graph directly
# render_graph(my_graph, layout = "tree")


```

```{r, fig.height=12, out.width=12}
require(DiagrammeR)
grViz("
digraph path_diagram {

  # a 'graph' statement
  graph [layout = dot, rankdir = LR, overlap = false, nodesep = 0.6, fontsize = 12, ranksep = 3]

  # several 'node' statements
  node [shape = circle,
        fixedsize = false,
        fontname = Helvetica,
        width = 1]
  X1; X2; X3; X4; X15; X16; X17; X18

  node [shape = circle,
        fixedsize = false,
        fillcolor = orange,
        width = 0.8] // sets as circles
  P1; P2
  
  node [shape = circle,
        fixedsize = false,
        fillcolor = PowderBlue,
        width = 0.8] // sets as circles
  T2; T4; T5; T6
  
  node [shape = circle,
        fixedsize = false,
        fillcolor = pink,
        width = 0.8] // sets as circles
  D2; D4
  
  node [shape = rectangle,
        fixedsize = true,
        color = grey,
        fillcolor = grey,
        width = 2] // sets as circles
  H1; H4
  
  node [shape = circle,
        fixedsize = false,
        fillcolor = green,
        width = 1] // sets as circles
  V1; V2; V3; V4; V5; V6; V7; V8; V9; V10

  # several 'edge' statements
  edge [color = grey, style = dashed, arrowhead = none, penwidth = 1]
  {X1 X2 X3 X4}  -> P1
  {X15 X16 X17 X18}  -> P2
  
  {X1 X17} -> T2
  {X4 X15} -> T4
  {X3 X16} -> T5
  {X2 X18} -> T6

  {X1 X2 X3 X4} -> D2
  {X15 X16 X17 X18} -> D4
  
  edge [color = black, style = solid, arrowhead = normal]
  D2 -> H1 [label = '-0.3885*']
  D2 -> H4 [label = '-0.2293*']
  D4 -> H1 [label = '-0.2369*']
  D4 -> H4 [label = '-0.0010', color = grey]
  
  P1 -> H1 [label = '0.3373*']
  P1 -> H4 [label = '-0.8116*'] 
  P2 -> H1 [label = '0.2459*']  
  P2 -> H4 [label = '-0.0183*']
  
  T2 -> H1 [label = '-0.4752*']  
  T2 -> H4 [label = '0.1164*']  
  T4 -> H1 [label = '-0.0292*']
  T4 -> H4 [label = '0.2734*'] 
  T5 -> H1 [label = '-0.1423*']
  T5 -> H4 [label = '-0.1802*']
  T6 -> H1 [label = '0.1518*']
  T6 -> H4 [label = '-0.2601*']
  
  H1 -> V1 [label = '0.0243*'] 
  H1 -> V2 [label = '0.1639*']
  H1 -> V3 [label = -0.0047, color = grey]
  H1 -> V4 [label = '0.0058*']
  H1 -> V5 [label = '0.0062*']
  H1 -> V6 [label = -0.0004, color = grey]
  H1 -> V7 [label = '0.0405*']
  H1 -> V8 [label = 0.0216, color = grey]
  H1 -> V9 [label = '0.0631*']
  H1 -> V10 [label = '0.3325*']
  
  H4 -> V1 [label = -0.0049, color = grey] 
  H4 -> V2 [label = '-0.1415*']
  H4 -> V3 [label = 0.0032, color = grey]
  H4 -> V4 [label = -0.0018, color = grey]
  H4 -> V5 [label = -0.0023, color = grey]
  H4 -> V6 [label = 0.0007, color = grey]
  H4 -> V7 [label = 0.0334, color = grey]
  H4 -> V8 [label = -0.0039, color = grey]
  H4 -> V9 [label = -0.0420, color = grey]
  H4 -> V10 [label = '-0.2536*']
}
")
```
