# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

insider <- function(data, cfd_factors, column_factor, cfd_indicators, train_indicator, latent_dim, lambda, alpha, tuning, tol = 1e-5, max_iter = 20000L) {
    .Call(`_insider_insider`, data, cfd_factors, column_factor, cfd_indicators, train_indicator, latent_dim, lambda, alpha, tuning, tol, max_iter)
}

rcpparma_hello_world <- function() {
    .Call(`_insider_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_insider_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_insider_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_insider_rcpparma_bothproducts`, x)
}

